# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7d673f2ee123f86909678dfaf631b45332a492139f285237f74be70ca862fd5de5ebcb49bd85d0e84e09cbb10e87dd30da9102067132e273acc37235b5273c1

test:
  secret_key_base: fa9bdcef50782af2b23cc15e56ddf5190a91d7957b9fefe19c084d66f21db413b8e95dd5b4c4080578dad9103a16ef3adedf66c3d69794906f852fa278e7e7ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
